global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "nvidia_jetson"
    static_configs:
    - targets: ["jetson-exporter:8000"]

  - job_name: "named process"
    static_configs:
    - targets: ["process-expoerter:9256"]

  - job_name: "pi1"
    static_configs:
    - targets: ["192.168.0.50:9100"]

  - job_name: "pi2"
    static_configs:
    - targets: ["192.168.0.60:9100"]

  - job_name: "pi3"
    static_configs:
    - targets: ["192.168.0.70:9100"]
